apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facturas-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - facturas.pedroortiz.com
      secretName: facturas-tls
