apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: facturas-control

resources:
  - ../../base
  - cluster-issuer.yaml
  - db-init-job.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - path: ingress-tls-patch.yaml
    target:
      kind: Ingress
      name: facturas-ingress
