[mypy]
plugins = sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
check_untyped_defs = True

[mypy-backend.app.models.*]
disable_error_code = arg-type, assignment, var-annotated, misc

[mypy-backend.app.api.endpoints.*]
disable_error_code = arg-type, assignment, var-annotated, attr-defined
