apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: facturas-control
data:
  AZURE_CONTENT_ENDPOINT: "https://aifoundry-resource-9030.services.ai.azure.com/"
  AZURE_STORAGE_CONTAINER: "facturas-proveedores"
  BACKEND_CORS_ORIGINS: "https://facturas.pedroortiz.com"
