apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: facturas-control

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

images:
  - name: facturas-backend
    newTag: latest
  - name: facturas-frontend
    newTag: latest
